### ISSUE TITLE
2 small issuess

### ISSUE THREAD

**Issue by piotrkunicki** [GavickPro/GK-Widget-Rules#7]
1. Notice: Undefined index: gk_widget_rules in /Applications/MAMP/htdocs/events/wp-content/plugins/gk-widget-rules/front-end.php on line 154
2. When you add new widget - it looks like:
   ![screenshot](https://cloud.githubusercontent.com/assets/2950258/3978909/12a11aee-284e-11e4-82da-63c3601c331f.jpg) (Chrome, Firefox)
   When you save the widget, everything is ok.

**Comment by dziudek** [comment]
1) Fixed:

https://github.com/GavickPro/GK-Widget-Rules/commit/2f4979b5731ed036d7db2cb0ae2a818708479c3f
https://github.com/GavickPro/GK-Widget-Rules/commit/5b736292290441b331a964cc9e6eb3b2ad2a0de3

2) Please refresh the CSS code - I didn't noticed this issue and I've checked the code - the container have the `clear: both;` property.

**Comment by piotrkunicki** [comment]
It's ok now.
